version: '3.8'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: zhaosheng123
      MYSQL_DATABASE: nacos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis/redis-stack:7.2.0-v10
    container_name: redis
    environment:
      - REDIS_ARGS=--requirepass zhaosheng123
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: nacos
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: zhaosheng123
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: zhaosheng123
    ports:
      - "31589:31589"
      - "31590:31590"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":31590" --address ":31589"

  mongodb:
    image: mongo:6.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zhaosheng123
      MONGO_INITDB_DATABASE: sapientiacloud_edupivot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init/mongodb:/docker-entrypoint-initdb.d
    command: mongod --auth

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,INTERNAL://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      CLUSTER_ID: '5YYJ085NRrijVFg9SLnVJA'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  mysql_data:
  redis_data:
  minio_data:
  mongodb_data:
  kafka_data: