input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["sapientiacloud-edupivot-all-logs"]
    group_id => "logstash-consumer"
    codec => "json"
  }
}

# 过滤器 (Filter)
# 如果日志是 JSON (如上 codec => "json")，
# 它会自动解析。如果是普通文本，可能需要
filter {
  # (暂时为空)
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "springboot-logs-%{+YYYY.MM.dd}"
  }

  # 同时在 Logstash 控制台打印日志，方便调试
  # stdout { codec => rubydebug }
}