/*
 Combined SQL File: mg_course_record + mg_course_record_student
 Generated by ChatGPT (GPT-5)
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

/*
 Navicat Premium Dump SQL

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80031 (8.0.31)
 Source Host           : localhost:3306
 Source Schema         : sapientiacloud_edupivot

 Target Server Type    : MySQL
 Target Server Version : 80031 (8.0.31)
 File Encoding         : 65001

 Date: 24/10/2025 19:56:26
*/

SET NAMES utf8mb4;

-- ----------------------------
-- Table structure for mg_course_record
-- ----------------------------
DROP TABLE IF EXISTS `mg_course_record`;
CREATE TABLE `mg_course_record`  (
  `id` binary(16) NOT NULL COMMENT '课程记录ID',
  `course_id` binary(16) NOT NULL COMMENT '关联课程ID',
  `teacher_id` binary(16) NOT NULL COMMENT '授课教师系统用户ID',
  `course_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '课程名称',
  `course_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '课程内容简介',
  `classroom_type` int NULL DEFAULT NULL COMMENT '教室类型 (0=小型教室, 1=中型教室, 2=大型教室, 3=超大型教室)',
  `layout_rows` int NULL DEFAULT NULL COMMENT '行数 (仅传统布局或对齐布局使用)',
  `layout_columns` int NULL DEFAULT NULL COMMENT '列数 (仅传统布局或对齐布局使用)',
  `start_time` datetime NULL DEFAULT NULL COMMENT '课程开始时间',
  `over_time` datetime NULL DEFAULT NULL COMMENT '课程结束时间',
  `status` tinyint(1) NULL DEFAULT 0 COMMENT '课程状态 (0=未开始, 1=进行中, 2=已结束, 3=已取消)',
  `is_deleted` tinyint(1) NULL DEFAULT 0 COMMENT '逻辑删除标记 (0=未删除, 1=已删除)',
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_course_id`(`course_id` ASC) USING BTREE,
  INDEX `idx_teacher_id`(`teacher_id` ASC) USING BTREE,
  CONSTRAINT `fk_course_record_course` FOREIGN KEY (`course_id`) REFERENCES `mg_course` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '课程教学记录表(含3D教室布局参数及行列信息)' ROW_FORMAT = DYNAMIC;


/*
 Navicat Premium Dump SQL

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80031 (8.0.31)
 Source Host           : localhost:3306
 Source Schema         : sapientiacloud_edupivot

 Target Server Type    : MySQL
 Target Server Version : 80031 (8.0.31)
 File Encoding         : 65001

 Date: 24/10/2025 19:56:33
*/

SET NAMES utf8mb4;

-- ----------------------------
-- Table structure for mg_course_record_student
-- ----------------------------
DROP TABLE IF EXISTS `mg_course_record_student`;
CREATE TABLE `mg_course_record_student`  (
  `record_id` binary(16) NOT NULL COMMENT '课程记录ID',
  `student_id` binary(16) NOT NULL COMMENT '学生ID',
  `course_id` binary(16) NOT NULL COMMENT '课程ID',
  `seat_index` int NULL DEFAULT NULL COMMENT '座位编号(从0开始)',
  `location_x` float NULL DEFAULT NULL COMMENT '3D坐标X(横向)',
  `location_y` float NULL DEFAULT NULL COMMENT '3D坐标Y(高度)',
  `location_z` float NULL DEFAULT NULL COMMENT '3D坐标Z(纵深)',
  `rotation_y` float NULL DEFAULT NULL COMMENT '朝向角度(弧度制)',
  `seat_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'normal' COMMENT '座位状态 (normal, marked, reserved, occupied)',
  `attendance_status` tinyint(1) NULL DEFAULT 0 COMMENT '出勤状态 (0=未签到, 1=已签到, 2=缺席)',
  `participation_score` float NULL DEFAULT NULL COMMENT '课堂互动得分(可选)',
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`record_id`, `student_id`) USING BTREE,
  INDEX `idx_course_id`(`course_id` ASC) USING BTREE,
  INDEX `idx_student_id`(`student_id` ASC) USING BTREE,
  CONSTRAINT `fk_record_student_course` FOREIGN KEY (`course_id`) REFERENCES `mg_course` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_record_student_record` FOREIGN KEY (`record_id`) REFERENCES `mg_course_record` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_record_student_student` FOREIGN KEY (`student_id`) REFERENCES `mg_student` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '课程教学学生参与表(含3D座位坐标与朝向)' ROW_FORMAT = DYNAMIC;


SET FOREIGN_KEY_CHECKS = 1;




/*
 Navicat Premium Dump SQL

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80031 (8.0.31)
 Source Host           : localhost:3306
 Source Schema         : sapientiacloud_edupivot

 Target Server Type    : MySQL
 Target Server Version : 80031 (8.0.31)
 File Encoding         : 65001

 Date: 16/11/2025 15:32:11
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for mg_classroom_question
-- ----------------------------
DROP TABLE IF EXISTS `mg_classroom_question`;
CREATE TABLE `mg_classroom_question`  (
  `id` binary(16) NOT NULL COMMENT '主键ID（唯一标识一条课堂-题目关联记录）',
  `classroom_id` binary(16) NOT NULL COMMENT '关联课堂ID（对应mg_course_record.id）',
  `question_id` binary(16) NOT NULL COMMENT '关联题目ID（关联题库中题目的的唯一标识）',
  `publish_order` int NULL DEFAULT 0 COMMENT '题目发布顺序（控制课堂内题目展示的先后顺序）',
  `score` float NULL DEFAULT 0 COMMENT '题目分值值（支持小数）',
  `is_required` tinyint(1) NULL DEFAULT 0 COMMENT '是否必答 (0=选答, 1=必答)',
  `start_time` datetime NULL DEFAULT NULL COMMENT '题目可作答开始时间（为空则默认随课堂开始）',
  `end_time` datetime NULL DEFAULT NULL COMMENT '题目作答截止时间（为空则默认随课堂结束）',
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `is_deleted` tinyint(1) NULL DEFAULT 0 COMMENT '逻辑删除标记 (0=未删除, 1=已删除)',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `idx_classroom_question`(`classroom_id` ASC, `question_id` ASC, `is_deleted` ASC) USING BTREE COMMENT '确保同一课堂内题目不重复',
  INDEX `idx_classroom_id`(`classroom_id` ASC) USING BTREE COMMENT '快速查询某课堂的所有题目',
  INDEX `idx_question_id`(`question_id` ASC) USING BTREE COMMENT '查询题目关联的课堂'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '课堂-题目关联表（记录课堂发布的题目及配置信息）' ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
