pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis-plus:
  type-aliases-package: com.dayz.sapientiacloud_edupivot.course.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  httpclient:
    enabled: true

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH_DATABASE}
      type-mapper: none


MONGODB_HOST: localhost
MONGODB_PORT: 27017
MONGODB_DATABASE: sapientiacloud_edupivot
MONGODB_USERNAME: root
MONGODB_PASSWORD: zhaosheng123
MONGODB_AUTH_DATABASE: admin

livekit:
  host: ${LIVEKIT_HOST}
  api-key: ${LIVEKIT_API_KEY}
  api-secret: ${LIVEKIT_API_SECRET}
  token-ttl-seconds: 7200
  room:
    empty-timeout-seconds: 300
    departure-timeout-seconds: 20
    max-participants: 500
  egress:
    enable: false

LIVEKIT_HOST: http://localhost:7880
LIVEKIT_API_KEY: "x9!r3@k7#b2% f5^j8&m1*t4 (y6) g9q3z2w5v7s1d4h6n8"
LIVEKIT_API_SECRET: "7p@2w!5d#8g%3j^6l&9n*1r (y4) t7z3x5c8v2b4f6k1m9"