spring:
  cloud:
    gateway:
      routes:
        - id: SapientiaCloud-EduPivot--system
          uri: lb://SapientiaCloud-EduPivot--system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--auth
          uri: lb://SapientiaCloud-EduPivot--auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--minIO
          uri: lb://SapientiaCloud-EduPivot--minIO
          predicates:
            - Path=/api/minIO/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--teacher
          uri: lb://SapientiaCloud-EduPivot--teacher
          predicates:
            - Path=/api/teacher/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--student
          uri: lb://SapientiaCloud-EduPivot--student
          predicates:
            - Path=/api/student/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--course
          uri: lb://SapientiaCloud-EduPivot--course
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--classroom-ws
          uri: lb:ws://SapientiaCloud-EduPivot--classroom
          predicates:
            - Path=/api/classroom/ws/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--classroom
          uri: lb://SapientiaCloud-EduPivot--classroom
          predicates:
            - Path=/api/classroom/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--live-sse
          uri: lb://SapientiaCloud-EduPivot--live
          predicates:
            - Path=/api/live/subscribe,/api/live/unsubscribe
          filters:
            - StripPrefix=1
        - id: SapientiaCloud-EduPivot--live
          uri: lb://SapientiaCloud-EduPivot--live
          predicates:
            - Path=/api/live/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--live-sse-alias
          uri: lb://SapientiaCloud-EduPivot--live
          predicates:
            - Path=/api/celestial-hub/live/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--celestial-hub
          uri: lb://SapientiaCloud-EduPivot--celestial-hub
          predicates:
            - Path=/api/celestial-hub/**
          filters:
            - StripPrefix=2

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3

cache:
  caffeine:
    spec: maximumSize=500,expireAfterWrite=10m

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    root: INFO
    com.dayz: INFO

REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_USERNAME:
REDIS_PASSWORD: zhaosheng123
