feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

spring:
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://edupivot.xyz/api/auth/oauth2/callback/github
            scope: 
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://api.edupivot.xyz/login/oauth/access_token
            user-info-uri: https://api.edupivot.xyz/user
            user-name-attribute: login

app:
  http:
    proxy:
      enabled: false
      host: ${PROXY_HOST}
      port: ${PROXY_PORT}

GITHUB_CLIENT_ID: Ov23lifIKc7byE3a1RCu
GITHUB_CLIENT_SECRET: 81b20fb6dbcdc9f44ccbcbca39d971a56aed798f