spring:
  cloud:
    gateway:
      routes:
        - id: SapientiaCloud-EduPivot--system
          uri: lb://SapientiaCloud-EduPivot--system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=2
        - id: SapientiaCloud-EduPivot--auth
          uri: lb://SapientiaCloud-EduPivot--auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3

cache:
  caffeine:
    spec: maximumSize=500,expireAfterWrite=10m

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_USERNAME:
REDIS_PASSWORD: zhaosheng123